### ISSUE TITLE
"ImportError: No module named 'docutils'" for upgrade to 0.11.0

### ISSUE THREAD

**Issue by alexbepple** [mpv-player/homebrew-mpv#83]
Unfortunately the upgrade fails.

```
==> Downloading https://github.com/mpv-player/mpv/archive/v0.11.0.tar.gz
==> Downloading from https://codeload.github.com/mpv-player/mpv/tar.gz/v0.11.0
######################################################################## 100.0%
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12
######################################################################## 100.0%
==> python3 setup.py install --prefix=/usr/local/Cellar/mpv/0.11.0/libexec
==> Downloading https://waf.io/waf-1.8.12
######################################################################## 100.0%
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/0.11.0 --enable-zsh-com
==> python3 waf install
Last 15 lines from /Users/ab/Library/Logs/Homebrew/mpv/03.python3:
+ install /usr/local/Cellar/mpv/0.11.0/share/applications/mpv.desktop (from etc/mpv.desktop)
+ install /usr/local/Cellar/mpv/0.11.0/etc/mpv/encoding-profiles.conf (from etc/encoding-profiles.conf)
+ install /usr/local/Cellar/mpv/0.11.0/share/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
+ install /usr/local/Cellar/mpv/0.11.0/share/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
+ install /usr/local/Cellar/mpv/0.11.0/share/icons/hicolor/64x64/apps/mpv.png (from etc/mpv-icon-8bit-64x64.png)
Traceback (most recent call last):
  File "/usr/local/Cellar/mpv/0.11.0/libexec/bin/rst2man.py", line 21, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named 'docutils'

Waf: Leaving directory `/private/tmp/mpv20150925-12100-y1o9ob/mpv-0.11.0/build'
Build failed
 -> task in 'rst2man' failed (exit status 1):
	{task 4410960976: rst2man mpv.rst -> mpv.1}
' /usr/local/Cellar/mpv/0.11.0/libexec/bin/rst2man.py ../DOCS/man/mpv.rst DOCS/man/mpv.1 '
```

Just in case I ran it again and got the same result:
```
==> Upgrading 1 outdated package, with result:
mpv-player/mpv/mpv 0.11.0
==> Upgrading mpv-player/mpv/mpv
==> Downloading https://github.com/mpv-player/mpv/archive/v0.11.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/mpv-0.11.0.tar.gz
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12
Already downloaded: /Library/Caches/Homebrew/mpv--docutils-0.12.tar.gz
==> python3 setup.py install --prefix=/usr/local/Cellar/mpv/0.11.0/libexec
==> Downloading https://waf.io/waf-1.8.12
Already downloaded: /Library/Caches/Homebrew/mpv--waf-1.8.12
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/0.11.0 --enable-zsh-com
==> python3 waf install
Last 15 lines from /Users/ab/Library/Logs/Homebrew/mpv/03.python3:
+ install /usr/local/Cellar/mpv/0.11.0/share/applications/mpv.desktop (from etc/mpv.desktop)
+ install /usr/local/Cellar/mpv/0.11.0/etc/mpv/encoding-profiles.conf (from etc/encoding-profiles.conf)
+ install /usr/local/Cellar/mpv/0.11.0/share/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
+ install /usr/local/Cellar/mpv/0.11.0/share/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
+ install /usr/local/Cellar/mpv/0.11.0/share/icons/hicolor/64x64/apps/mpv.png (from etc/mpv-icon-8bit-64x64.png)
Traceback (most recent call last):
  File "/usr/local/Cellar/mpv/0.11.0/libexec/bin/rst2man.py", line 21, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named 'docutils'

Waf: Leaving directory `/private/tmp/mpv20150925-12929-10sr687/mpv-0.11.0/build'
Build failed
 -> task in 'rst2man' failed (exit status 1):
	{task 4362103832: rst2man mpv.rst -> mpv.1}
' /usr/local/Cellar/mpv/0.11.0/libexec/bin/rst2man.py ../DOCS/man/mpv.rst DOCS/man/mpv.1 '
```

Not sure which other details are needed. Here are some.

```
> brew --version
0.9.5 (git revision 3d798; last commit 2015-09-25)

> python3 --version
Python 3.4.2

> sw_vers -productVersion
10.10.5
```

**Comment by Argon-** [comment]
That's a problem various people (including me) have encountered. IIRC the formula is building docutils but putting it into `/usr/local/lib/python3.5/site-packages` instead of `/usr/local/lib/python3.4/site-packages`. As for why this happens... I have no idea.

Two solutions: the python3 homebrew formula has currently version `3.5`. Once you upgrade your python3 it will look for packages in `...python3.5/site-packages` and it'll work.
Otherwise, use `pip3 install docutils` to install it manually into the correct `site-packages` directory for your current python3 version.

**Comment by alexbepple** [comment]
@Argon- Thanks, that helped.
